backend:
  name: github
  branch: main # Branch where CMS changes will be committed
  repo: JenFranko/portfolio # Path to your Github repository
  use_large_media_transforms_in_media_library: false
media_folder: "src/assets/images" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/images"

collections:
  - name: "home"
    label: "Home"
    folder: "src/content/home"
    create: false
    fields:
      - name: "name"
        widget: "string"
        required: true
      - label: "Intro"
        name: "intro"
        widget: "markdown"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "home"
